backend:
  name: git-gateway
  branch: master
media_folder: public/img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Meus Posts'
        name: 'home'
        file: 'content/home.md'
        fields:
          - label: 'Posts'
            name: "posts"
            widget: list
            fields:
              - {label: 'Título', name: 'title', widget: 'string' }
              - {label: 'Publish Date', name: 'date', widget: 'datetime' }
              - {label: "Descrição", name: "description", widget: "text"}
              - {label: 'Imagem', name: 'thumbnail', widget: 'image', required: true }
              - {label: "Sobre o post", name: "about", widget: "markdown" }
