backend:
  name: git-gateway
  branch: master
media_folder: "img/"
collections:
  - name: 'posts' # Used in routes, ie.: /admin/collections/:slug/edit
    identifier_field: name
    label: 'Posts' # Used in the UI
    label_singular: 'Post' # Used in the UI, ie: "New Post"
    description: >
      Posts sobre tecnologia e programacao
    folder: 'content/blog'
    slug: '{{slug}}'
    summary: 'Titulo: {{name}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'Título', name: 'name', widget: 'string' }
      - {label: "Descrição", name: "description", widget: "text"}
      - {label: 'Imagem', name: 'thumbnail', widget: 'image' ,required: false}
      - {label: "Sobre o post", name: "about", widget: "markdown" }
